{
  "formatVersion": "1.1",
  "component": {
    "group": "leaf",
    "module": "leaf",
    "version": "Leaf1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId": "yhcyrt2aozhcbgc4d7s5fjvpxa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "leaf-Leaf1.5.1.jar",
          "url": "leaf-Leaf1.5.1.jar",
          "size": 261693,
          "sha512": "f02b7c84892a2129d9418356a18f4a5b5483505abfa37c34e531b0371cffd18141452d2e0ab21b4035dd5514a10827bf75421fc61945fb5518e1844660bd30e3",
          "sha256": "f67ea4d9e856a950e535d4e5028d880cf5fea0934cea018abcf14b77877e5bbf",
          "sha1": "d8e968745aa8d197066219edb191bfc23869fe60",
          "md5": "908617ee0c208ae2364f23f76a2dcaf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.openjfx",
          "module": "javafx-graphics",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-graphics",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-swing",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-swing",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        },
        {
          "group": "org.openjfx",
          "module": "javafx-base",
          "version": {
            "requires": "11.0.2"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "javafx-base",
              "type": "jar",
              "extension": "jar",
              "classifier": "mac"
            }
          }
        }
      ],
      "files": [
        {
          "name": "leaf-Leaf1.5.1.jar",
          "url": "leaf-Leaf1.5.1.jar",
          "size": 261693,
          "sha512": "f02b7c84892a2129d9418356a18f4a5b5483505abfa37c34e531b0371cffd18141452d2e0ab21b4035dd5514a10827bf75421fc61945fb5518e1844660bd30e3",
          "sha256": "f67ea4d9e856a950e535d4e5028d880cf5fea0934cea018abcf14b77877e5bbf",
          "sha1": "d8e968745aa8d197066219edb191bfc23869fe60",
          "md5": "908617ee0c208ae2364f23f76a2dcaf3"
        }
      ]
    }
  ]
}
